### ISSUE TITLE
Sega Saturn RG40XX-V

### ISSUE THREAD

**Issue by paladinperry** [knulli-cfw/distribution#142]
### Knulli build version

21st July release

### Your architecture

RG40XX-V

### Issue description

Hey guys. Thanks for the amazing OS.
Just the same issue as everyone else.
A lot of slow down , stuttering on Sega Saturn and only 1-2 choices for emu on this.
The Stock OS is managing really well.
I'm hoping one day you will incorporate something so we can solely use Knulli for all our gaming on this device.
Thank you so much for the amazing OS again

### Detailed reproduction steps

Play most saturn games

### Details of any attempts to fix this yourself

Tried going into advanced game options and running via any available emu options
lowered resolution
made sure threaded 3d was set to on
etc

### Details of any modifications you have made to Knulli.

none

**Comment by Gregoloco** [comment]
Hello, if I may, I want to add that there may be a kind of integration issue or bug which induces a some slowdowns during saturn emulation as I sometimes have some part of the Knulli UI flashing on the screen while I play a Saturn game, and then the device seems in a stange unstable state (with part of interface flashing) when I quit the game... And I have to reboot the RG35XXSP so that everything is ok again.

**Comment by Mikhailzrick** [comment]
There’s a check now to ensure only one instance of ES is running. That should take care of your second issue. Saturn is a pretty difficult system to emulate. AFAIK stock uses some specific 32bit version that can perform a bit faster. But at this time Saturn emulation will always be problematic with the h700 devices.

closing as the only issue reported has been resolved.

**Comment by Gregoloco** [comment]
I will not reopen... But when I read :

> [...] Saturn is a pretty difficult system to emulate. AFAIK stock uses some specific 32bit version that can perform a bit faster. But at this time Saturn emulation will always be problematic with the h700 devices. [...]

Then I simply would like to kindly indicate that it is a fact that Saturn can run almost perfectly well on the RG35XX/40xx lwhen using the stock firmware, so there must be something Knulli can do to improve the current situation ;-) 
= today, even when booting a first game on the console after turning it on, i.e. with no risk of double execution, the result if way way far from what we can obtain on Stock firmware (= unplayable vs completly playable for most games).

Example = https://www.youtube.com/watch?v=uLmUlsIID1c

But I love Knulli so much that I use it and will continue to use it even without Saturn support...  maybe I just want Knulli to be too good :-)

**Comment by paladinperry** [comment]
Cheers guys 

I fully appreciate the Knulli team.
And I am no way disrespecting their efforts.

I know it plays on stock OS well and id love not to have to switch fw as I do genuinely love Knulli.

If you guys implement anything in the future, please do let us know 

As this would be a huge win.

Thanks all

**Comment by Nahojii** [comment]
> There’s a check now to ensure only one instance of ES is running. That should take care of your second issue. Saturn is a pretty difficult system to emulate. AFAIK stock uses some specific 32bit version that can perform a bit faster. But at this time Saturn emulation will always be problematic with the h700 devices.
> 
> closing as the only issue reported has been resolved.

Seems to still happen though on latest build though. Or hasn't this been updated yet? The issue with 2 running instances of ES. At least on rg35xx-h.

**Comment by Mikhailzrick** [comment]
> > There’s a check now to ensure only one instance of ES is running. That should take care of your second issue. Saturn is a pretty difficult system to emulate. AFAIK stock uses some specific 32bit version that can perform a bit faster. But at this time Saturn emulation will always be problematic with the h700 devices.
> > closing as the only issue reported has been resolved.
> 
> Seems to still happen though on latest build though. Or hasn't this been updated yet? The issue with 2 running instances of ES. At least on rg35xx-h.

It should be impossible for it to run two instances of emulation station. Are you on the latest firefly public release?

**Comment by unnatixlr8** [comment]
Please fix the issue. Saturn games are running at 5 FPS on the Knulli Gladiator firmware. Works fine in stock OS. Please reopen and look into the issue.

**Comment by GreenGuru23** [comment]
Trimui Brick at 5 FPS to. I cant play Saturn
