### ISSUE TITLE
error at root password change

### ISSUE THREAD

**Issue by fedekrum** [knulli-cfw/distribution#79]
### Knulli build version

40-dev-d3b520f949 2024/07/21 02:18

### Your architecture

rg35xx-h

### Issue description

i am getting an error while trying to change root passwd

```
[root@KNULLI /userdata/system]# batocera-config setRootPassword
cat: '/sys/class/net/eth/address': No such file or directory
** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
[root@KNULLI /userdata/system]#
```
Model: sun50iw9
System: Linux 4.9.170
Architecture: aarch64
Board: rg35xx-h
CPU Cores:  / CPU Threads: 4
CPU Max Frequency: 1512 MHz
Temperature: 59°C
Available Memory: 758/973 MB
Display Resolution: 640x480
Display Refresh Rate: .Hz
Data Partition Format: ext4
Data Partition Available Space: 52G
Network IP Address: 192.168.0.21
Battery: 100%
OS version: 40-dev-d3b520f949 2024/07/21 02:18

### Detailed reproduction steps

execute "batocera-config setRootPassword" as root on terminal

### Details of any attempts to fix this yourself

no

### Details of any modifications you have made to Knulli.

no

**Comment by HoroTW** [comment]
Huhu, just to make sure we are on the same page:
1. Menu -> System settings -> Security -> set Enforce Security to on
2. Reboot (after changing this setting, for the temporary root password go to Menu -> System Settings -> Security and check the new random password)
3. `batocera-config setRootPassword [yourPassword]` # You will get the above error but it should work anyway.
4. Reboot
5. Your new password should work now.

**Comment by HoroTW** [comment]
Despite working I created a small PR so there are no warnings/errors anymore when executing the commands (Also fixed the underling issue and not just silencing them ^^)

**Comment by HoroTW** [comment]
Can confirm this is now fixed in new builds :wink:, so you (or someone that has the rights for it) can close this issue 😊

**Comment by HoroTW** [comment]
@fedekrum would you please close the issue or is it not fixed for you?

**Comment by xenium1024** [comment]
Unfortunately I'm also having this issue, but with the current release build (firefly 2024/12/04 03:10). So it appears that it's actually not fixed, at least not for my device (RG Cube XX). Note that in my case there is an additional asterisk in the error message (i.e. "/sys/class/net/eth*/address" vs "/sys/class/net/eth/address" as reported by fedekrum.)
```
_  ___   _ _   _ _     _     ___
| |/ / \ | | | | | |   | |   |_ _|
| ' /|  \| | | | | |   | |    | |
| . \| |\  | |_| | |___| |___ | |
|_|\_\_| \_|\___/|_____|_____|___|

Model: Anbernic_RG_CubeXX
System: Linux 4.9.170
Architecture: aarch64
Board: rg-cubexx
CPU Cores:  / CPU Threads: 4
CPU Max Frequency: 1416 MHz
Temperature: 44°C
Available Memory: 750/972 MB
Display Resolution: 720x720
Display Refresh Rate: Hz
Data Partition Format: exfat
Data Partition Available Space: 54G
Network IP Address: 192.168.2.143
Battery: 83%
OS version: firefly 2024/12/04 03:10 []

[root@RGCUBEXX /userdata/system]# batocera-config setRootPassword testpasswd
cat: '/sys/class/net/eth*/address': No such file or directory
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
[root@RGCUBEXX /userdata/system]#
```

**Comment by xenium1024** [comment]
I forgot to mention that it DOES properly change the password, I'm just reporting that it's still spitting out the error message in the current build.

**Comment by HoroTW** [comment]
Hmm interesting, I'm a bit short on time at the moment, but I'll look into it sometime (if not someone else does it faster :-P)
